#!/usr/bin/env python3
"""P6 iter-94 schema validator + measured-block coverage audit.

Vein (c) of the P5P8 brief: build a CI-style schema validation script that
every registry entry must pass against registry/schema.json. Combines with
vein (b) — coverage audit — by computing per-leaf null-population rates
across all 35 entries and surfacing the gaps as a ranked "pending gaps" table.

Stdlib + jsonschema. No external deps beyond jsonschema (already installed in
worktree). Outputs (5 files in platform_hybrid/experiments/results/p5p8/):

- p6_iter94_validation.json   : per-entry validation record (pass/fail + detail)
- p6_iter94_validation.tsv    : per-entry summary table (35 rows)
- p6_iter94_field_coverage.tsv: per-leaf null-population rate across the corpus
- p6_iter94_pending_gaps.tsv  : ranked pending-gap action list
- p6_iter94_crosscheck.json   : cross-check vs registry/measured_block_audit.json

Gap classification (severity-ordered):
  HIGH   SCHEMA-VIOLATION         entry fails jsonschema validation against schema.json
  MEDIUM MEASURED-BLOCK-MISSING   variant_delta declares zero measured[] rows AND the
                                  notes do not contain "intentionally null" / "no same-
                                  stack arm" / "fabricatory" (legitimate null)
  MEDIUM CITATION-INCOMPLETE      variant_delta has bibkey but missing arxiv AND notes
                                  do not flag it as a "transparent placeholder"
  LOW    CITATION-INCOMPLETE      variant_delta missing bibkey
  INFO   RED-FLAG-LEAF            a min_report leaf has null-rate > 50% across the
                                  20 stack entries (reporting-coverage red flag)

Cross-check: registry/measured_block_audit.json was generated by an older
audit script; re-validate each variant_delta entry independently and report
any (stale_audit_measured_count != current_measured_n) discrepancies.
"""
import argparse
import json
import pathlib
import sys
from collections import defaultdict

import jsonschema

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent.parent
REG = ROOT / "registry"
ENT = REG / "entries"
OUT = ROOT / "experiments" / "results" / "p5p8"

NULL_THRESHOLD = 0.50  # null-rate above which a leaf is "red-flagged"

# Phrases that legitimately declare a measured-block as "intentional null"
# (cited from the canonical delta_ppo / delta_reinforce / delta_liteppo notes)
INTENTIONAL_NULL_PHRASES = (
    "intentionally null",
    "no same-stack",
    "no same stack",
    "fabricatory",
    "would be fabricatory",
)


def _flatten(obj, prefix=""):
    """Yield (dot.path, value) for every leaf in a nested dict; skip lists/dicts."""
    if isinstance(obj, dict):
        for k, v in obj.items():
            yield from _flatten(v, prefix + k + ".")
    else:
        yield prefix.rstrip("."), obj


def _load_entry(p):
    try:
        return json.loads(p.read_text()), None
    except Exception as e:
        return None, f"json-parse-error:{e}"


def _validate_one(validator, rec):
    """Run jsonschema against one entry. Return list of error strings."""
    errs = []
    try:
        validator.validate(rec)
    except jsonschema.ValidationError as e:
        errs.append(f"jsonschema:{e.message} at {list(e.absolute_path)}")
    return errs


def _coverage_min_report(rec):
    """Fraction of min_report leaves that are non-null (covers 7 items)."""
    mr = rec.get("min_report", {})
    total, nonnull = 0, 0
    for item in mr.values():
        if isinstance(item, dict):
            for v in item.values():
                total += 1
                if v is not None:
                    nonnull += 1
    return (nonnull / total) if total else 0.0, nonnull, total


def _is_intentional_null(rec):
    """True iff notes contain one of the INTENTIONAL_NULL_PHRASES."""
    notes = (rec.get("notes") or "").lower()
    return any(phrase in notes for phrase in INTENTIONAL_NULL_PHRASES)


def _is_transparent_placeholder(rec):
    notes = (rec.get("notes") or "").lower()
    return "transparent placeholder" in notes or "placeholder" in notes


def _citation_status(rec):
    """For variant_delta records only — stack records do not have citation by
    schema design. Returns (ok: bool, status: str)."""
    if rec.get("record_type") != "variant_delta":
        return True, "n/a-stack-record"
    cite = rec.get("citation") or {}
    bibkey = cite.get("bibkey")
    arxiv = cite.get("arxiv")
    if not bibkey:
        return False, "missing-bibkey"
    if not arxiv:
        if _is_transparent_placeholder(rec):
            return True, "transparent-placeholder"
        return False, "missing-arxiv-and-not-flagged"
    return True, "ok"


def _measured_status(rec):
    """True if entry has measured[] with at least 1 row, plus its length."""
    m = rec.get("measured") or []
    if isinstance(m, list):
        return len(m) > 0, len(m)
    return False, 0


def _has_provenance(rec):
    """Stack records carry provenance.source_artifacts + provenance.date_recorded."""
    p = rec.get("provenance") or {}
    return bool(p.get("source_artifacts")) and bool(p.get("date_recorded"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=20260705)
    ap.add_argument("--strict", action="store_true",
                    help="exit non-zero if any HIGH-severity gap is present")
    args = ap.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)

    schema = json.loads((REG / "schema.json").read_text())
    Validator = jsonschema.Draft202012Validator
    validator = Validator(schema)

    per_entry = []
    leaf_counts = defaultdict(lambda: [0, 0])
    for p in sorted(ENT.glob("*.json")):
        rec, parse_err = _load_entry(p)
        if parse_err:
            per_entry.append({
                "entry_id": p.stem, "file": p.name, "record_type": None,
                "schema_pass": False, "errors": [parse_err],
                "min_report_coverage": 0.0, "min_report_nonnull": 0,
                "min_report_total": 0, "citation_ok": False,
                "citation_status": "load-failed",
                "measured_n": 0, "measured_present": False,
                "intentional_null": False, "provenance_complete": False,
            })
            continue
        rt = rec.get("record_type")
        errs = _validate_one(validator, rec)
        cov, nn, tot = _coverage_min_report(rec)
        cok, cstat = _citation_status(rec)
        mpres, mlen = _measured_status(rec)
        intentional = _is_intentional_null(rec)
        prov = _has_provenance(rec)
        per_entry.append({
            "entry_id": rec.get("id", p.stem), "file": p.name,
            "record_type": rt, "schema_pass": (len(errs) == 0),
            "errors": errs, "min_report_coverage": round(cov, 4),
            "min_report_nonnull": nn, "min_report_total": tot,
            "citation_ok": cok, "citation_status": cstat,
            "measured_n": mlen, "measured_present": mpres,
            "intentional_null": intentional,
            "provenance_complete": prov,
        })
        if rt == "stack":
            for path, val in _flatten(rec.get("min_report", {})):
                leaf_counts[path][1] += 1
                if val is not None:
                    leaf_counts[path][0] += 1

    # 1. validation.tsv
    val_tsv = OUT / "p6_iter94_validation.tsv"
    cols = ["entry_id", "record_type", "schema_pass",
            "min_report_coverage", "min_report_nonnull", "min_report_total",
            "citation_ok", "citation_status", "measured_n",
            "intentional_null", "provenance_complete", "n_errors"]
    with val_tsv.open("w") as f:
        f.write("\t".join(cols) + "\n")
        for r in per_entry:
            row = [
                r["entry_id"], str(r["record_type"]),
                "PASS" if r["schema_pass"] else "FAIL",
                f"{r['min_report_coverage']:.4f}",
                str(r["min_report_nonnull"]), str(r["min_report_total"]),
                "yes" if r["citation_ok"] else "no",
                r["citation_status"], str(r["measured_n"]),
                "yes" if r["intentional_null"] else "no",
                "yes" if r["provenance_complete"] else "no",
                str(len(r["errors"])),
            ]
            f.write("\t".join(row) + "\n")

    # 2. validation.json (full)
    summary = {
        "n_entries": len(per_entry),
        "n_schema_pass": sum(1 for r in per_entry if r["schema_pass"]),
        "n_schema_fail": sum(1 for r in per_entry if not r["schema_pass"]),
        "n_stack_records": sum(1 for r in per_entry if r["record_type"] == "stack"),
        "n_variant_delta_records": sum(
            1 for r in per_entry if r["record_type"] == "variant_delta"),
        "n_with_measured": sum(1 for r in per_entry if r["measured_present"]),
        "n_without_measured": sum(1 for r in per_entry if not r["measured_present"]),
        "n_intentional_null_measured": sum(
            1 for r in per_entry if r["intentional_null"] and not r["measured_present"]),
        "n_citation_ok": sum(1 for r in per_entry if r["citation_ok"]),
        "n_provenance_complete": sum(
            1 for r in per_entry if r["provenance_complete"]),
        "mean_min_report_coverage": round(
            sum(r["min_report_coverage"] for r in per_entry) / len(per_entry), 4),
        "null_threshold": NULL_THRESHOLD,
    }
    val_json = OUT / "p6_iter94_validation.json"
    val_json.write_text(json.dumps(
        {"summary": summary, "per_entry": per_entry}, indent=2))

    # 3. field_coverage.tsv (per-leaf null rate for stack entries)
    fcov_tsv = OUT / "p6_iter94_field_coverage.tsv"
    with fcov_tsv.open("w") as f:
        cols = ["leaf", "n_nonnull", "n_total", "nonnull_rate",
                "null_rate", "red_flag"]
        f.write("\t".join(cols) + "\n")
        rows = sorted(leaf_counts.items(),
                      key=lambda kv: (kv[1][0] / max(1, kv[1][1]), kv[0]))
        for leaf, (nn, tot) in rows:
            rate = nn / tot if tot else 0.0
            red = "YES" if (1 - rate) > NULL_THRESHOLD else "no"
            f.write("\t".join([
                leaf, str(nn), str(tot),
                f"{rate:.4f}", f"{1-rate:.4f}", red,
            ]) + "\n")

    # 4. pending_gaps.tsv
    gap_tsv = OUT / "p6_iter94_pending_gaps.tsv"
    gaps = []
    for r in per_entry:
        if not r["schema_pass"]:
            for err in r["errors"]:
                gaps.append({
                    "severity": "HIGH", "category": "SCHEMA-VIOLATION",
                    "entry": r["entry_id"], "detail": err,
                    "action": "fix entry to pass jsonschema validation",
                })
        if (r["record_type"] == "variant_delta"
                and not r["measured_present"]
                and not r["intentional_null"]):
            gaps.append({
                "severity": "MEDIUM", "category": "MEASURED-BLOCK-MISSING",
                "entry": r["entry_id"],
                "detail": "variant_delta declares zero measured[] rows "
                          "and notes do not flag it as intentional-null",
                "action": ("add measured[] rows from existing repo data, "
                           "or add 'intentionally null' + reason to notes"),
            })
        if (r["record_type"] == "variant_delta"
                and not r["citation_ok"]
                and r["citation_status"] != "n/a-stack-record"):
            sev = "MEDIUM" if "arxiv" in r["citation_status"] else "LOW"
            gaps.append({
                "severity": sev, "category": "CITATION-INCOMPLETE",
                "entry": r["entry_id"],
                "detail": f"citation_status={r['citation_status']}",
                "action": ("add bibkey+arxiv OR add 'transparent placeholder' "
                           "to notes (see delta_liteppo for canonical phrasing)"),
            })
    with gap_tsv.open("w") as f:
        cols = ["severity", "category", "entry", "detail", "action"]
        f.write("\t".join(cols) + "\n")
        sev_rank = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
        for g in sorted(gaps, key=lambda x: (sev_rank[x["severity"]], x["entry"])):
            f.write("\t".join([
                g["severity"], g["category"], g["entry"], g["detail"],
                g["action"],
            ]) + "\n")

    # 5. crosscheck.json (vs registry/measured_block_audit.json)
    stale_audit_path = REG / "measured_block_audit.json"
    crosscheck = {"stale_audit_path": str(stale_audit_path.relative_to(ROOT)),
                  "discrepancies": []}
    if stale_audit_path.exists():
        stale = json.loads(stale_audit_path.read_text())
        stale_by_id = {e["delta_id"]: e for e in stale.get("per_entry", [])}
        for r in per_entry:
            if r["record_type"] != "variant_delta":
                continue
            sid = r["entry_id"]
            if sid not in stale_by_id:
                continue
            stale_mc = stale_by_id[sid].get("measured_count", 0)
            actual_mc = r["measured_n"]
            if stale_mc != actual_mc:
                crosscheck["discrepancies"].append({
                    "entry": sid,
                    "stale_audit_says_measured_count": stale_mc,
                    "validator_says_measured_n": actual_mc,
                    "interpretation": (
                        "audit script is STALE; entry now has measured block"
                        if actual_mc > stale_mc else
                        "entry has fewer rows than audit claims"),
                })
    (OUT / "p6_iter94_crosscheck.json").write_text(
        json.dumps(crosscheck, indent=2))

    # 6. headline print
    print(f"[p6-iter94] validated {summary['n_entries']} entries against "
          f"schema.json (draft-2020-12)")
    print(f"[p6-iter94] schema_pass={summary['n_schema_pass']} "
          f"schema_fail={summary['n_schema_fail']}")
    print(f"[p6-iter94] stack_records={summary['n_stack_records']} "
          f"variant_delta_records={summary['n_variant_delta_records']}")
    print(f"[p6-iter94] with_measured={summary['n_with_measured']} "
          f"without_measured={summary['n_without_measured']} "
          f"intentional_null={summary['n_intentional_null_measured']}")
    print(f"[p6-iter94] citation_ok={summary['n_citation_ok']} "
          f"provenance_complete={summary['n_provenance_complete']}")
    print(f"[p6-iter94] mean_min_report_coverage="
          f"{summary['mean_min_report_coverage']:.4f}")
    print(f"[p6-iter94] n_pending_gaps={len(gaps)}")
    red = [leaf for leaf, (nn, tot) in leaf_counts.items()
           if tot and (1 - nn/tot) > NULL_THRESHOLD]
    print(f"[p6-iter94] n_red_flag_leaves(null>{NULL_THRESHOLD:.0%})={len(red)}")
    print(f"[p6-iter94] crosscheck_discrepancies="
          f"{len(crosscheck['discrepancies'])}")
    print(f"[p6-iter94] wrote {val_tsv.name}, {val_json.name}, "
f"{fcov_tsv.name}, {gap_tsv.name}, p6_iter94_crosscheck.json")

    if args.strict and any(g["severity"] == "HIGH" for g in gaps):
        sys.exit(1)


if __name__ == "__main__":
    main()