#!/usr/bin/env python3
"""Iter 26 helper: regenerate the `delta_id` enum in registry/schema.json.

After the iter-26 schema bump, the `variant_deltas_applied[].delta_id`
field is constrained by an `enum` listing every valid
`registry/entries/delta_*.json` stem. This script regenerates that enum
from the entries folder so a contributor who adds a new delta record
gets validation for free.

Run from the worktree root:
    python3 platform_modal/scripts/p5p8/regenerate_schema_delta_enum.py

Side effects:
  - Mutates registry/schema.json (preserving all other fields).
  - Validates every entry still passes the bumped schema.
  - Fails non-zero if any entry would now fail validation.

Stdlib only.
"""
from __future__ import annotations

import json
import pathlib
import sys

try:
    import jsonschema  # only used to verify the new schema validates all entries
except ImportError:
    jsonschema = None  # tolerate absence; just skip the verification step

WORKTREE = pathlib.Path(__file__).resolve().parent.parent.parent
SCH = WORKTREE / "registry" / "schema.json"
ENT = WORKTREE / "registry" / "entries"


def main():
    schema = json.loads(SCH.read_text())
    delta_ids = sorted(p.stem for p in ENT.glob("delta_*.json"))
    if not delta_ids:
        print("ERROR: no delta_*.json entries found in", ENT, file=sys.stderr)
        sys.exit(2)
    # Locate the variant_deltas_applied.items.properties.delta_id node
    try:
        node = schema["$defs"]["stack_record"]["properties"][
            "variant_deltas_applied"]["items"]["properties"]["delta_id"]
    except (KeyError, TypeError) as e:
        print("ERROR: could not locate variant_deltas_applied[].delta_id "
              "in schema:", e, file=sys.stderr)
        sys.exit(3)
    node["enum"] = delta_ids
    node["description"] = (
        "Must point to a registry/entries/delta_*.json record. "
        "Enum is regenerated by platform_modal/scripts/p5p8/"
        "regenerate_schema_delta_enum.py whenever a delta is added."
    )
    SCH.write_text(json.dumps(schema, indent=2))
    print(f"regenerated delta_id enum with {len(delta_ids)} ids:")
    for d in delta_ids:
        print(f"  - {d}")
    if jsonschema is not None:
        n_ok, n_fail = 0, 0
        for p in sorted(ENT.glob("*.json")):
            rec = json.loads(p.read_text())
            try:
                jsonschema.validate(rec, schema)
                n_ok += 1
            except jsonschema.ValidationError as e:
                n_fail += 1
                print(f"  FAIL {p.stem}: {e.message[:120]}", file=sys.stderr)
        print(f"validation: {n_ok}/{n_ok+n_fail} entries PASS after enum regen")
        if n_fail:
            sys.exit(4)


if __name__ == "__main__":
    main()
