#!/usr/bin/env python3
"""Create a clean blind-review submission bundle for reports/final.

This copies only the anonymized paper source and supporting files into a fresh
export directory, excluding generated build artifacts and non-anonymous sources.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DEFAULT_OUT = ROOT / "blind-review-package"

INCLUDE = [
    "grpo_agentic_llm_paper_anonymous.tex",
    "references.bib",
    "nips_style.sty",
    "supplementary_appendix.tex",
    "SUBMISSION_README.md",
    "SUBMISSION_CHECKLIST.md",
]

WRITE_README = """# Blind Review Package

This directory was generated by `prepare_blind_review_package.py`.

Included files:
- anonymized paper source
- bibliography
- style file
- supplementary appendix
- submission instructions/checklist

Excluded on purpose:
- non-anonymous paper sources
- generated build artifacts (`.aux`, `.log`, `.out`, compiled PDFs)
- local scratch files

Before submission, run from the repository root:

```bash
python run_all_audits.py
```
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare blind-review package")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output directory")
    parser.add_argument("--force", action="store_true", help="Overwrite existing output directory")
    args = parser.parse_args()

    out_dir = args.out.resolve()
    if out_dir.exists():
        if not args.force:
            raise SystemExit(f"Output directory already exists: {out_dir} (use --force)")
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    for rel in INCLUDE:
        src = ROOT / rel
        if not src.exists():
            raise SystemExit(f"Missing required file: {src}")
        shutil.copy2(src, out_dir / src.name)

    (out_dir / "README.txt").write_text(WRITE_README)

    print(f"Prepared blind-review package at: {out_dir}")
    print("Included files:")
    for rel in INCLUDE:
        print(f"  - {rel}")


if __name__ == "__main__":
    main()
