import csv, math
import os; S=os.path.dirname(os.path.abspath(__file__))+"/"
R="/Users/arvind/Developer/agentic_repos/tinker-rl-lab/platform_hybrid/experiments/results/"
OUT="/Users/arvind/Developer/agentic_repos/tinker-rl-lab/outputs/PES_Phase2_Third_Review_2026-09-24/thesis/figures/fig_scaling_null.tex"
orig=open(S+"fig_scaling_null.orig.tex").read()
head=orig[:orig.index("\\begin{document}")]
head=head.replace("tag/.style={font=\\tiny,","tag/.style={font=\\footnotesize,").replace("keyfont/.style={font=\\fontsize{4.8}{5.7}\\selectfont}","keyfont/.style={font=\\footnotesize}")
rows=list(csv.DictReader(open(R+"scaling_law_extended_frontier.tsv"),delimiter="\t"))
order=["Qwen3.5-4B","Qwen3-8B","Llama-3.1-8B-Instruct","gpt-oss-20B","Qwen3.5-27B","Qwen3-30B-MoE","Qwen3-30B-MoE-Inst","Qwen3-32B","Nemotron-120B","Qwen3-235B-MoE","DeepSeek-V3.1","Kimi-K2-Thinking"]
by={r["model"]:r for r in rows}
pl={r["metric"]:r for r in csv.DictReader(open(R+"scaling_law_power_law.tsv"),delimiter="\t")}
pts=[]
for i,m in enumerate(order,1):
    r=by[m]; N=float(r["params_B"]); mu=float(r["r_mean"]); sd=math.sqrt(float(r["r_var"])); n=int(r["n_steps"])
    up=min(sd,1-mu); lo=min(sd,mu)  # whisker clipped to the [0,1] reward range
    pts.append((i,m,N,mu,sd,up,lo,n))
# tag placement: (anchor, xshift, yshift) chosen per point to avoid overprint
place={1:"east,xshift=-3pt",2:"east,xshift=-3pt",3:"west,xshift=3pt",4:"east,xshift=-3pt",5:"east,xshift=-3pt",
       6:"east,xshift=-3pt,yshift=-4pt",7:"east,xshift=-3pt",8:"west,xshift=3pt,yshift=-4pt",9:"west,xshift=3pt",10:"west,xshift=3pt",11:"east,xshift=-3pt",12:"west,xshift=3pt"}
o=[head,"\\begin{document}\n"]
o.append("""% fig_scaling_null -- cross-scale GRPO reward vs model scale, 12 single-seed anchors.
% Generated by gen_scaling_null.py from
%   platform_hybrid/experiments/results/scaling_law_extended_frontier.tsv (params_B, r_mean,
%   r_var, n_steps): point = r_mean, whisker = +-1 SD of the logged per-step reward
%   (sqrt(r_var)), clipped to [0,1]; open marker = fewer than 10 logged steps.
%   platform_hybrid/experiments/results/scaling_law_power_law.tsv (slope, se_slope, perm_p):
%   panel (b) whisker = 1.96 * se_slope.
\\begin{tikzpicture}
\\begin{axis}[
  name=A, width=14.0cm, height=5.6cm, xmode=log, xmin=3.3, xmax=2200, ymin=0, ymax=1.12,
  xtick={4,8,20,30,100,300,1000}, xticklabels={4,8,20,30,100,300,1000},
  ytick={0,0.2,0.4,0.6,0.8,1.0},
  tick label style={font=\\footnotesize, /pgf/number format/fixed},
  xlabel={model scale $N$ (parameters, billions; log scale)},
  ylabel={mean per-step reward $\\bar R$}, label style={font=\\footnotesize},
  title={\\textbf{(a)} $\\bar R$ vs.\\ scale, 12 single-seed GRPO anchors}, title style={font=\\footnotesize},
  grid=major, grid style={black!8}, tick align=outside, clip=false,
  error bars/y dir=both, error bars/y explicit,
]
\\fill[black!13] (axis cs:3.3,0.5448) rectangle (axis cs:2200,0.7372);
\\draw[black!70, thick, dashed] (axis cs:3.3,0.6410) -- (axis cs:2200,0.6410);
\\node[font=\\footnotesize, text=black!75, fill=white, fill opacity=0.85, text opacity=1, inner sep=1.4pt, anchor=east]
     at (axis cs:2150,0.60) {constant model (AICc) and noise-floor band};
""")
full=" ".join(f"({N:g},{mu:.4f}) += (0,{up:.4f}) -= (0,{lo:.4f})" for i,m,N,mu,sd,up,lo,n in pts if n>=10)
short=" ".join(f"({N:g},{mu:.4f}) += (0,{up:.4f}) -= (0,{lo:.4f})" for i,m,N,mu,sd,up,lo,n in pts if n<10)
o.append(f"\\addplot[only marks, mark=*, mark size=2.1pt, black, error bars/error bar style={{black!55}}] coordinates {{{full}}};\n")
o.append(f"\\addplot[only marks, mark=o, mark size=2.3pt, thick, black, error bars/error bar style={{black!55, densely dashed}}] coordinates {{{short}}};\n")
for i,m,N,mu,sd,up,lo,n in pts:
    o.append(f"\\node[tag, anchor={place[i]}] at (axis cs:{N:g},{mu:.4f}) {{{i}}};\n")
o.append("\\end{axis}\n")
o.append("""\\begin{axis}[
  at={($(A.south west)+(0,-2.0cm)$)}, anchor=north west,
  width=7.4cm, height=5.4cm, xmin=-0.40, xmax=0.66, ymin=-0.7, ymax=6.7,
  ytick={0,1,2,3,4,5,6},
  yticklabels={$R(t{=}1)$,$R(t{=}T)$,$\\bar R$ (mean),$\\hat R$ (peak),$\\mathrm{Var}(R)$,$P(R{=}0)$,$P(R{>}0.5)$},
  xtick={-0.3,0,0.3,0.6}, tick label style={font=\\footnotesize, /pgf/number format/fixed},
  xlabel={OLS slope per decade of $N$ (each metric's own units)}, label style={font=\\footnotesize},
  title={\\textbf{(b)} slope of each metric, 95\\% CI}, title style={font=\\footnotesize},
  grid=major, grid style={black!8}, tick align=outside, clip=false,
]
\\draw[black, thick] (axis cs:0,-0.7) -- (axis cs:0,6.7);
""")
mets=["r_first","r_final","r_mean","r_peak","r_var","zero_frac","frac_above_0p5"]
co=" ".join(f"({float(pl[m]['slope_per_log10N']):.4f},{k}) +- ({1.96*float(pl[m]['se_slope']):.4f},0)" for k,m in enumerate(mets))
o.append(f"\\addplot[only marks, mark=*, mark size=2.0pt, black, thick, error bars/.cd, x dir=both, x explicit, error bar style={{line width=0.7pt, draw=black}}] coordinates {{{co}}};\n")
o.append("\\node[font=\\footnotesize, text=black!65, anchor=west] at (axis cs:0.68,6.55) {perm.\\ $p$};\n")
for k,m in enumerate(mets):
    o.append(f"\\node[font=\\footnotesize, text=black!65, anchor=west] at (axis cs:0.70,{k}) {{{float(pl[m]['perm_p_value']):.2f}}};\n")
o.append("""\\end{axis}
\\node[keyfont, align=left, anchor=north west] at ($(A.south east)+(-5.3cm,-2.1cm)$)
 {\\begin{tabular}{@{}r@{\\hspace{3pt}}l@{}}
""")
for i,m,N,mu,sd,up,lo,n in pts:
    nm=m.replace("-Instruct","-Inst")
    o.append(f"  {i} & {nm} ({n} steps)\\\\\n")
o.append(" \\end{tabular}};\n\\end{tikzpicture}\n\\end{document}\n")
open(OUT,"w").write("".join(o))
for p in pts: print(p)
