"""Fail-closed control plane for the flagship conformance pilot."""

from .dashboard_export import (
    DashboardExportError,
    EntropicGatingData,
    GradientRecoveryData,
    SpectralTrajectoryData,
    export_comparative_dashboard_html,
    export_gating_density_heatmap_html,
    export_gradient_recovery_html,
    export_spectral_trajectory_html,
    prepare_entropic_gating_data,
    prepare_gradient_recovery_data,
    prepare_spectral_trajectory_data,
)
from .entropic_gating import (
    EntropicGatingError,
    GivensEntropyGate,
    apply_givens_rotation_pair,
    compute_attention_entropy,
    compute_entropy_density,
    eliminate_noise_components,
    givens_rotation_angle,
)
from .objective import (
    Condition,
    ConditionTrace,
    GradientDiagnostic,
    ObjectiveContractError,
    condition_loss,
    condition_trace,
    entropic_givens_grpo,
    gradient_diagnostic,
    spectral_legendre_grpo,
)
from .protocol import (
    AuthorizationError,
    PilotProtocol,
    PilotUnit,
    ProtocolError,
    build_screening_plan,
    execution_blockers,
    load_protocol,
)
from .spectral_attention import (
    LegendreSpectralRouting,
    SpectralAttentionError,
    compute_legendre_polynomials,
    legendre_basis,
    legendre_grid,
    legendre_spectral_projection,
    spectral_pairwise_distance,
)

__all__ = [
    "AuthorizationError",
    "Condition",
    "ConditionTrace",
    "DashboardExportError",
    "EntropicGatingData",
    "EntropicGatingError",
    "GivensEntropyGate",
    "GradientDiagnostic",
    "GradientRecoveryData",
    "LegendreSpectralRouting",
    "ObjectiveContractError",
    "PilotProtocol",
    "PilotUnit",
    "ProtocolError",
    "SpectralAttentionError",
    "SpectralTrajectoryData",
    "apply_givens_rotation_pair",
    "build_screening_plan",
    "compute_attention_entropy",
    "compute_entropy_density",
    "compute_legendre_polynomials",
    "condition_loss",
    "condition_trace",
    "eliminate_noise_components",
    "entropic_givens_grpo",
    "execution_blockers",
    "export_comparative_dashboard_html",
    "export_gating_density_heatmap_html",
    "export_gradient_recovery_html",
    "export_spectral_trajectory_html",
    "givens_rotation_angle",
    "gradient_diagnostic",
    "legendre_basis",
    "legendre_grid",
    "legendre_spectral_projection",
    "load_protocol",
    "prepare_entropic_gating_data",
    "prepare_gradient_recovery_data",
    "prepare_spectral_trajectory_data",
    "spectral_legendre_grpo",
    "spectral_pairwise_distance",
]

