import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';import {pathToFileURL}from'node:url';import{FileBlob,PresentationFile}from'@oai/artifact-tool';
const root=await fs.realpath('/Users/arvind/Developer/tinker-rl-lab'),tmp=path.join(root,'.codex-pptx/phase2-review-2026-09-12'),out=path.join(root,'outputs/PES_Phase2_Review_2026-09-12');
const skill='/Users/arvind/.codex/plugins/cache/openai-primary-runtime/presentations/26.905.11957/skills/presentations';
const python='/Users/arvind/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3';
const source=path.join(root,'outputs/public_portfolio_2026-09-05/presentation/E1_E14_Public_Research_Update_v15.pptx'),final=path.join(out,'PES_Phase2_Review_ArvindCR_2026-09-12_Review.pptx');
process.env.RUNTIME_NODE_MODULES='/Users/arvind/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';process.env.RUNTIME_NODE='/Users/arvind/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/bin/node';process.env.RUNTIME_PYTHON=python;process.env.RUNTIME_BIN_DIR='/Users/arvind/.cache/codex-runtimes/codex-primary-runtime/dependencies/bin/override';
const{finalizePresentation}=await import(pathToFileURL(path.join(skill,'container_tools/artifact_tool_utils.mjs')).href);
await finalizePresentation({workspaceDir:root,candidatePath:path.join(tmp,'candidate.pptx'),finalPath:final,pythonExecutable:python,integrityValidatorPath:path.join(skill,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(skill,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit',...[2,3,4,5,9,10,11,12].flatMap(n=>['--require-native-table-slide',String(n)])],explicitTotalSlideCount:13,requiredNativeTableOwnerSlides:[2,3,4,5,9,10,11,12],requiredNativeChartOwnerSlides:[6,7,8],requiredEmbeddedWorkbookChartOwnerSlides:[6,7,8],fontPolicy:{basis:'reference',families:['Helvetica Neue'],referencePath:source,referenceSha256:crypto.createHash('sha256').update(await fs.readFile(source)).digest('hex')},verifyArtifactToolImport:true,receiptPath:path.join(tmp,'validation-review.json')});
const p=await PresentationFile.importPptx(await FileBlob.load(final));
for(let i=0;i<p.slides.items.length;i++){const blob=await p.slides.items[i].export({format:'png',scale:1});await fs.writeFile(path.join(tmp,`review-${i+1}.png`),new Uint8Array(await blob.arrayBuffer()));}
console.log(final);
