#!/usr/bin/env python3
"""Verify the reviewed public snapshot locally, without rebuilding or network access.

This checks file integrity, copied code definitions and public navigation. It is
not an authenticity proof, privacy scan or reproduction of omitted executions.
The frozen publication manifest is an input, never regenerated by this tool.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import math
from pathlib import Path, PurePosixPath
import re
from urllib.parse import unquote, urlsplit

# Support both `python tools/<checker>.py` and module/test imports.
if __package__:
    from ._strict import require
else:
    from _strict import require


ROOT = Path(__file__).resolve().parents[1]
REVISION = "reports/public_revision_2026-10-03"
MANIFEST = f"{REVISION}/PUBLICATION_MANIFEST.json"
PUBLIC_ROOTS = (REVISION, "research/public_analysis", "research/public_results")
SNAPSHOT_EXTRAS = {".gitignore", "README.md", "SUBMISSION.md", "tests/test_public_analysis.py"}
NAVIGATION = (
    f"{REVISION}/README.md",
    f"{REVISION}/thesis/README.md",
    f"{REVISION}/addendum/README_PUBLIC.md",
    "research/public_analysis/README.md",
    "research/public_results/README.md",
)
SCOPE = (
    "Public file integrity, copied source definitions, navigation and recorded scientific "
    "consistency only; not source authentication, independent scientific review, "
    "a privacy certification or replay of omitted executions."
)
HEX256 = re.compile(r"[0-9a-f]{64}\Z")


def strict_json(path):
    def pairs(items):
        result = {}
        for key, value in items:
            require(key not in result, f"{path.name}: duplicate JSON key {key!r}")
            result[key] = value
        return result

    def nonfinite(value):
        raise ValueError(f"{path.name}: nonfinite JSON value {value}")

    def finite_float(value):
        parsed = float(value)
        require(math.isfinite(parsed), f"{path.name}: nonfinite JSON value {value}")
        return parsed

    return json.loads(
        path.read_text(encoding="utf-8"),
        object_pairs_hook=pairs,
        parse_constant=nonfinite,
        parse_float=finite_float,
    )


def safe_file(root, relative):
    """Reject ambiguous paths and symlinks before reading any manifest-selected file."""
    require(isinstance(relative, str) and relative, "file path must be nonempty text")
    path = PurePosixPath(relative)
    require(
        not path.is_absolute()
        and path.as_posix() == relative
        and ".." not in path.parts
        and "\\" not in relative
        and "\x00" not in relative,
        f"unsafe or noncanonical relative path: {relative!r}",
    )
    candidate = root
    for part in path.parts:
        candidate = candidate / part
        require(not candidate.is_symlink(), f"symlink is not a publication file: {relative}")
    require(candidate.is_file(), f"missing publication file: {relative}")
    require(candidate.resolve().is_relative_to(root.resolve()), f"file escapes root: {relative}")
    return candidate


def sha256(path):
    with path.open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def snapshot_paths(root):
    """Inventory source inputs, excluding the builders' documented scratch outputs."""
    paths = set(SNAPSHOT_EXTRAS)
    for directory in PUBLIC_ROOTS:
        base = root / directory
        require(base.is_dir() and not base.is_symlink(), f"missing public directory: {directory}")
        for path in base.rglob("*"):
            local = path.relative_to(base)
            if any(
                part in {"build", "__pycache__"} or part.startswith(".") for part in local.parts
            ):
                continue
            relative = path.relative_to(root).as_posix()
            if relative in {MANIFEST, f"{REVISION}/thesis/thesis_master.tex"}:
                continue
            if path.is_file() or path.is_symlink():
                paths.add(relative)
    return paths


def verify_manifest(root, manifest_path=MANIFEST, expected_paths=None):
    manifest = strict_json(safe_file(root, manifest_path))
    require(isinstance(manifest, dict), "publication manifest must be an object")
    require(manifest.get("schema") == "public-scientific-release-v1", "unknown publication schema")
    entries = manifest.get("files")
    require(isinstance(entries, list) and entries, "publication manifest files must be nonempty")
    seen = set()
    total_bytes = 0
    for entry in entries:
        require(isinstance(entry, dict), "publication file entry must be an object")
        require(set(entry) == {"path", "bytes", "sha256"}, "invalid publication file entry fields")
        name = entry["path"]
        path = safe_file(root, name)
        require(name != manifest_path, "publication manifest cannot hash itself")
        require(name not in seen, f"duplicate publication path: {name}")
        seen.add(name)
        size = entry["bytes"]
        require(type(size) is int and size >= 0, f"invalid byte count: {name}")
        require(
            isinstance(entry["sha256"], str) and HEX256.fullmatch(entry["sha256"]),
            f"invalid SHA-256: {name}",
        )
        require(path.stat().st_size == size, f"publication byte count mismatch: {name}")
        require(sha256(path) == entry["sha256"], f"publication SHA-256 mismatch: {name}")
        total_bytes += size
    if expected_paths is not None:
        require(
            seen == set(expected_paths),
            "publication inventory mismatch: "
            f"unlisted={sorted(set(expected_paths) - seen)}; unexpected={sorted(seen - set(expected_paths))}",
        )
    return {"files_verified": len(seen), "bytes_verified": total_bytes}


def verify_source_definitions(root):
    package = "research/public_analysis"
    provenance = strict_json(safe_file(root, f"{package}/PROVENANCE.json"))
    require(isinstance(provenance, dict), "source provenance must be an object")
    modules = provenance.get("modules")
    require(isinstance(modules, dict) and modules, "source provenance modules must be nonempty")
    copied = 0
    for filename, metadata in modules.items():
        require(
            isinstance(filename, str)
            and PurePosixPath(filename).name == filename
            and filename.endswith(".py"),
            "source provenance needs a Python module basename",
        )
        source = safe_file(root, f"{package}/{filename}").read_text(encoding="utf-8")
        nodes = {}
        for node in ast.parse(source).body:
            name = None
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                name = node.name
            elif isinstance(node, ast.Assign) and isinstance(node.targets[0], ast.Name):
                name = node.targets[0].id
            if name is not None:
                require(name not in nodes, f"duplicate source definition: {filename}:{name}")
                nodes[name] = node
        require(isinstance(metadata, dict), f"invalid provenance metadata: {filename}")
        definitions = metadata.get("selected_definition_source_sha256")
        require(
            isinstance(definitions, dict) and definitions, f"missing copied definitions: {filename}"
        )
        for name, expected in definitions.items():
            require(name in nodes, f"missing copied source definition: {filename}:{name}")
            require(
                isinstance(expected, str) and HEX256.fullmatch(expected),
                f"invalid definition digest: {filename}:{name}",
            )
            source_text = ast.get_source_segment(source, nodes[name])
            actual = hashlib.sha256(source_text.encode("utf-8")).hexdigest()
            require(actual == expected, f"copied source definition changed: {filename}:{name}")
            copied += 1
    return {"source_modules_verified": len(modules), "copied_definitions_verified": copied}


def verify_navigation(root):
    count = 0
    for name in NAVIGATION:
        path = safe_file(root, name)
        # These entry-point READMEs use simple inline Markdown links. Historical
        # paths in prose/code and external links are deliberately outside scope.
        for destination in re.findall(
            r"(?<!!)\[[^\]]+\]\(([^\s)]+)\)", path.read_text(encoding="utf-8")
        ):
            url = urlsplit(destination.strip("<>"))
            if url.scheme or url.netloc or not url.path:
                continue
            target = (path.parent / unquote(url.path)).resolve()
            require(target.is_relative_to(root.resolve()), f"navigation escapes root: {name}")
            require(target.is_file(), f"broken public navigation: {name} -> {destination}")
            count += 1
    require(count > 0, "no public navigation links found")
    return {"local_navigation_links_verified": count}


def check_public_release(root):
    root = Path(root).resolve()
    result = verify_manifest(root, expected_paths=snapshot_paths(root))
    result.update(verify_source_definitions(root))
    result.update(verify_navigation(root))
    return {"status": "PASS", **result, "scope": SCOPE}


def main(argv=None):
    cli = argparse.ArgumentParser(description=__doc__)
    cli.add_argument(
        "--root", type=Path, default=ROOT, help="Repository root (default: this checkout)"
    )
    args = cli.parse_args(argv)
    try:
        result = check_public_release(args.root)
    except (OSError, ValueError, TypeError, KeyError, SyntaxError) as exc:
        print(json.dumps({"status": "FAIL", "error": str(exc), "scope": SCOPE}, sort_keys=True))
        return 1
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
