# E1–E14 results — 5 September 2026

**2 full-suite results · 5 partial lanes · 7 externally blocked lanes. The experiment campaign is incomplete.**

This notebook reviews historical native results and reproduces the audit calculations. It executes without credentials or GPU allocation in Jupyter or Colab. It does not rerun the experiments or turn preflight checks into scores.

## Context and methods

The local native receipts were reconciled on 5 September 2026. E1 and E11 are single-seed full-suite outcomes, not a completed multi-seed research program. Twelve suite scores remain unavailable. Partial/recovery outcomes retain their original boundaries. The two E9 inference arms stay separate.

### Assumptions and scope

- Null means no admissible full-suite score, never zero performance.
- E1 retains all 731 cases in the denominator, including 18 failed or lost generations.
- E11 uses the canonical raw 312-instance denominator.
- The budget is the saved campaign ledger, not a current invoice or Colab balance.
- Notebook execution validates this report; it does not supply private provider tasks or a working inference runtime.

## Data

The dated audit snapshot is embedded for portability. Its SHA-256 is checked on load. Source paths and hashes are available in the companion `source_manifest.json`.

In [1]:
import json, hashlib, math
from collections import Counter
from html import escape
from IPython.display import display, HTML

SNAPSHOT_JSON = '{\n  "as_of_utc": "2026-09-05T02:44:27.910654+00:00",\n  "budget": {\n    "authorized_incremental_usd": 50.0,\n    "boundary": "Historical conservative accounting, not a refreshed invoice or Colab balance. No new paid allocation in this task.",\n    "counted_incremental_usd": 5.630100981793,\n    "ledger_recorded_at": "2026-08-30T02:14:48Z",\n    "recorded_remaining_usd": 44.369899018207\n  },\n  "caveats": [\n    "Two full-suite single-seed outcomes do not complete the broader multi-seed research program.",\n    "Partial and recovery outcomes are never interpreted as full-suite scores.",\n    "E9 legacy Tinker and merged-vLLM arms remain separate; heterogeneous competition scores are not averaged.",\n    "The first Spooky Author run retains only a submission preview; its complete submission is missing. A later same-program run has its complete submission.",\n    "Colab source-pin preflight for the alternative public portfolio does not evaluate the contracted E1-E14 suites.",\n    "Historical Colab canaries failed with out-of-memory and CUDA illegal-memory-access errors; they produced no suite result.",\n    "Provider trust, licenses, decontamination, full-suite execution and checkpoint gates still apply before any paid continuation."\n  ],\n  "complete_exact_suite_results": 2,\n  "e9_arms": {\n    "merged_vllm": {\n      "attempted_competition_ids": [\n        "alaska2-image-steganalysis",\n        "h-and-m-personalized-fashion-recommendations",\n        "hotel-id-2021-fgvc8",\n        "hubmap-kidney-segmentation",\n        "imet-2020-fgvc7",\n        "predict-volcanic-eruptions-ingv-oe",\n        "vesuvius-challenge-ink-detection"\n      ],\n      "graded_competition_ids": [\n        "h-and-m-personalized-fashion-recommendations"\n      ],\n      "local_artifact_gaps": [],\n      "native_graded_competitions": 1,\n      "receipt_count": 7,\n      "score": null,\n      "status_counts": {\n        "NATIVE_SINGLE_COMPETITION_GRADED": 1,\n        "NATIVE_SINGLE_COMPETITION_INVALID": 6\n      },\n      "unique_competitions": 7\n    },\n    "modal_streaming": {\n      "attempted_competition_ids": [\n        "AI4Code",\n        "aerial-cactus-identification",\n        "aptos2019-blindness-detection",\n        "billion-word-imputation",\n        "bms-molecular-translation",\n        "cassava-leaf-disease-classification",\n        "chaii-hindi-and-tamil-question-answering",\n        "champs-scalar-coupling",\n        "denoising-dirty-documents",\n        "detecting-insults-in-social-commentary",\n        "dog-breed-identification",\n        "dogs-vs-cats-redux-kernels-edition",\n        "facebook-recruiting-iii-keyword-extraction",\n        "freesound-audio-tagging-2019",\n        "google-quest-challenge",\n        "histopathologic-cancer-detection",\n        "hms-harmful-brain-activity-classification",\n        "jigsaw-toxic-comment-classification-challenge",\n        "jigsaw-unintended-bias-in-toxicity-classification",\n        "kuzushiji-recognition",\n        "leaf-classification",\n        "learning-agency-lab-automated-essay-scoring-2",\n        "lmsys-chatbot-arena",\n        "mlsp-2013-birds",\n        "multi-modal-gesture-recognition",\n        "new-york-city-taxi-fare-prediction",\n        "nfl-player-contact-detection",\n        "nomad2018-predict-transparent-conductors",\n        "osic-pulmonary-fibrosis-progression",\n        "petfinder-pawpularity-score",\n        "plant-pathology-2020-fgvc7",\n        "plant-pathology-2021-fgvc8",\n        "random-acts-of-pizza",\n        "smartphone-decimeter-2022",\n        "spooky-author-identification",\n        "stanford-covid-vaccine",\n        "statoil-iceberg-classifier-challenge",\n        "tabular-playground-series-dec-2021",\n        "tabular-playground-series-may-2022",\n        "tensorflow-speech-recognition-challenge",\n        "tensorflow2-question-answering",\n        "text-normalization-challenge-english-language",\n        "text-normalization-challenge-russian-language",\n        "tgs-salt-identification-challenge",\n        "the-icml-2013-whale-challenge-right-whale-redux",\n        "tweet-sentiment-extraction",\n        "us-patent-phrase-to-phrase-matching",\n        "uw-madison-gi-tract-image-segmentation",\n        "ventilator-pressure-prediction",\n        "whale-categorization-playground"\n      ],\n      "graded_competition_ids": [\n        "AI4Code",\n        "aerial-cactus-identification",\n        "aptos2019-blindness-detection",\n        "bms-molecular-translation",\n        "cassava-leaf-disease-classification",\n        "chaii-hindi-and-tamil-question-answering",\n        "champs-scalar-coupling",\n        "denoising-dirty-documents",\n        "detecting-insults-in-social-commentary",\n        "dog-breed-identification",\n        "dogs-vs-cats-redux-kernels-edition",\n        "freesound-audio-tagging-2019",\n        "google-quest-challenge",\n        "histopathologic-cancer-detection",\n        "jigsaw-toxic-comment-classification-challenge",\n        "leaf-classification",\n        "learning-agency-lab-automated-essay-scoring-2",\n        "lmsys-chatbot-arena",\n        "mlsp-2013-birds",\n        "new-york-city-taxi-fare-prediction",\n        "nomad2018-predict-transparent-conductors",\n        "osic-pulmonary-fibrosis-progression",\n        "petfinder-pawpularity-score",\n        "plant-pathology-2020-fgvc7",\n        "random-acts-of-pizza",\n        "smartphone-decimeter-2022",\n        "spooky-author-identification",\n        "stanford-covid-vaccine",\n        "statoil-iceberg-classifier-challenge",\n        "tabular-playground-series-dec-2021",\n        "tabular-playground-series-may-2022",\n        "tensorflow-speech-recognition-challenge",\n        "tensorflow2-question-answering",\n        "text-normalization-challenge-russian-language",\n        "the-icml-2013-whale-challenge-right-whale-redux",\n        "tweet-sentiment-extraction",\n        "us-patent-phrase-to-phrase-matching",\n        "uw-madison-gi-tract-image-segmentation",\n        "ventilator-pressure-prediction",\n        "whale-categorization-playground"\n      ],\n      "local_artifact_gaps": [\n        {\n          "file": "submission.csv",\n          "reason": "local file absent",\n          "receipt": "outputs/e9_mle_bench/modal_streaming/spooky-author-identification-92a9c2022e7e/receipt.json"\n        }\n      ],\n      "native_graded_competitions": 40,\n      "receipt_count": 97,\n      "score": null,\n      "status_counts": {\n        "AGENT_EXECUTION_FAILED": 51,\n        "NATIVE_SINGLE_COMPETITION_GRADED": 41,\n        "NATIVE_SINGLE_COMPETITION_INVALID": 5\n      },\n      "unique_competitions": 50\n    }\n  },\n  "experiment_completion_claimed": false,\n  "externally_blocked_lanes": 7,\n  "lanes": [\n    {\n      "benchmark_status": "SCORED_EXACT_SUITE",\n      "lane": "E1",\n      "name": "SWE-bench Pro",\n      "receipt": "outputs/modal_e1_e14/2026-08-16/e1_swe_bench_pro_full/seed1818/receipt.json",\n      "remaining_requirement": "None for this recorded single-seed evaluation; 18 failed/lost generations remain unresolved in the denominator.",\n      "result": "2/731 = 0.274% pass@1",\n      "scope": "731/731 terminal generations; 713 native evaluations; 14 generation failures; 4 artifact losses",\n      "score": 0.0027359781121751026,\n      "work_status": "LOCALLY_TERMINAL"\n    },\n    {\n      "benchmark_status": "PARTIAL_EXACT",\n      "blocker": "The official pin 422b9bb95deb8efe436becb0ed3c44be23611e10 has no controlling root licence or evaluation authorization, and no official hosted signed-result route was found. The other 16 tasks therefore remain unavailable for an authorized exact full-suite run.",\n      "lane": "E2",\n      "latest_correctness": "8/8 hidden scenes",\n      "latest_native_task_reward": 0.725611,\n      "name": "FrontierSWE",\n      "receipt": "outputs/e2_frontier_swe/e2_terminal_attempt_receipt_2026-08-22.json",\n      "recovery_normalized_task_score": 0.8628,\n      "remaining_requirement": "Revision-bound benchmark authorization and 16 remaining tasks; original Tinker checkpoint unavailable.",\n      "result": "1/17 tasks; replay normalized score 0.8628",\n      "scope": "1/17 official tasks",\n      "score": null,\n      "work_status": "LOCAL_SETUP_READY_PROVIDER_INPUT_REQUIRED"\n    },\n    {\n      "benchmark_status": "BLOCKED_EXTERNAL",\n      "blocker": "Private 80-task bundle, provider runtime/reset contract, native grader, and license are absent.",\n      "followup_message_id": "1a04b91dc27b4469",\n      "lane": "E3",\n      "name": "SDAB",\n      "remaining_requirement": "Private 80-task bundle, runtime/reset contract and native grader.",\n      "result": "No exact-suite result",\n      "score": null,\n      "work_status": "WAITING_PROVIDER"\n    },\n    {\n      "attempt_metric": 0.3115,\n      "benchmark_status": "PARTIAL_RECOVERY",\n      "blocker": "The exact public checkout, dataset, and 100/100 generated task artifacts are restored and passed 1,175 manifest checks with zero failures. Exact execution remains blocked: the receipt-based native-grader lower bound is approximately $59.45, above the remaining $44.369899018207 cap, and any future model/verifier run still requires the campaign W&B, immutable-checkpoint, native-verifier, provider, and hard-budget gates.",\n      "lane": "E4",\n      "name": "BankerToolBench",\n      "receipt": "outputs/modal_e1_e14/2026-08-16/e4_recovery_evidence_boundary_2026-08-22.json",\n      "remaining_requirement": "Working model/verifier endpoint and budget: the prior native-grader-only estimate exceeds the recorded remaining cap.",\n      "restoration_receipt": "outputs/e4_banker_toolbench/e4_public_restoration_receipt_2026-08-30.json",\n      "result": "1/100 tasks; recovery metric 0.3115",\n      "scope": "1/100 official tasks; the single replayed artifact met 37/128 task criteria",\n      "score": null,\n      "work_status": "LOCALLY_TERMINAL_FOR_AVAILABLE_ARTIFACT"\n    },\n    {\n      "alternative_route_cost_receipt": "outputs/e5_apex_agents/e5_merged_vllm_cost_scenarios_2026-08-30.json",\n      "asset_inventory_receipt": "outputs/e5_apex_agents/e5_asset_inventory_2026-08-30.json",\n      "attempt_prefix_mean_failure_as_zero": 0.05050505050505051,\n      "benchmark_status": "PARTIAL_EXACT",\n      "blocker": "The pinned 480-task task/rubric bundle and sealed manifest are present, but the full auxiliary task/gold asset payload is not materialized locally; repository metadata remains gated although authenticated access was previously unblocked. Merged vLLM would be a separate execution arm and cannot be combined with the 11-task Tinker prefix. The local Mac lacks CUDA and storage; same-model A100 scenarios are approximately $143 to $289 before environments, with native judging adding a $4.20 to $5.39 lower bound, all above the remaining $44.369899018207 cap.",\n      "lane": "E5",\n      "name": "APEX-Agents",\n      "receipt": "outputs/e5_apex_agents/e5_exact_sequential_prefix_aggregate_2026-08-22.json",\n      "remaining_requirement": "Working inference runtime, full auxiliary assets, sufficient budget and a declared execution protocol.",\n      "result": "11/480 attempted; 7 native-scored; prefix mean 0.050505",\n      "scope": "11/480 sequential tasks attempted; 7 native-scored, 3 unscored failures, 1 operator-interrupted",\n      "score": null,\n      "scored_receipt_mean": 0.07936507936507936,\n      "work_status": "LOCALLY_TERMINAL_UNDER_CURRENT_CAP"\n    },\n    {\n      "access_request": "https://github.com/Halluminate/WebBench/issues/2#issuecomment-5460052427",\n      "benchmark_status": "BLOCKED_EXTERNAL",\n      "blocker": "Official live environment/reset, ground truth, native scorer, and write authorization are absent.",\n      "followup_message_id": "1a04b91dfda3af97",\n      "lane": "E6",\n      "name": "WebBench",\n      "remaining_requirement": "Official live environment, reset procedure, ground truth and native scorer.",\n      "result": "No exact-suite result",\n      "score": null,\n      "work_status": "LOCAL_SETUP_READY_PROVIDER_INPUT_REQUIRED"\n    },\n    {\n      "attempt_reward": 0.0,\n      "benchmark_status": "PARTIAL_EXACT",\n      "blocker": "The official pin cbd86c7cd8519f01ae6b7ad7db7fdb653ea54f23 has no revision-controlled licence artifact: repository licence metadata is null, the licence endpoint is 404, and the README\'s Apache-2.0 claim points to a missing LICENSE file. No hosted signed-result route was found for an authorized complete 46-task run.",\n      "lane": "E7",\n      "name": "BinaryAudit",\n      "receipt": "outputs/e7_binaryaudit/2026-08-22_e7_paid_attempt_receipt.json",\n      "remaining_requirement": "Revision-bound benchmark authorization, working model runtime and the remaining 45 tasks.",\n      "result": "1/46 tasks; verifier reward 0.0 after agent error",\n      "scope": "1/46 official tasks; native verifier completed for the task, while the agent terminated at the paid bridge boundary",\n      "score": null,\n      "work_status": "LOCALLY_TERMINAL_FOR_AVAILABLE_TASK"\n    },\n    {\n      "access_request_receipt": "outputs/e8_lifescibench/contact_sales_submission_receipt_2026-08-24.json",\n      "benchmark_status": "BLOCKED_EXTERNAL",\n      "blocker": "Official task package, license, and native grader are absent.",\n      "lane": "E8",\n      "name": "LifeSciBench",\n      "remaining_requirement": "Official task package and native grader.",\n      "result": "0/750 tasks",\n      "scope": "0/750 official tasks",\n      "score": null,\n      "work_status": "WAITING_PROVIDER"\n    },\n    {\n      "benchmark_status": "PARTIAL_EXACT",\n      "blocker": "35 legacy competitions still lack native grades. Seven separate fresh merged-vLLM pilots produced one valid native single-competition grade and six invalid receipts; all are terminal no-resample evidence with zero legacy coverage increment. The original Tinker sampler checkpoint is deleted. The 75-competition primary aggregate, multi-seed mean/SEM, and training-contamination receipt remain incomplete.",\n      "continuation_recovery_receipts": [\n        "outputs/e9_mle_bench/modal_streaming/plant-pathology-2021-fgvc8-1afc1ef65a3a/receipt.json",\n        "outputs/e9_mle_bench/modal_streaming/jigsaw-unintended-bias-in-toxicity-classification-be21ca31edd2/receipt.json",\n        "outputs/e9_mle_bench/modal_streaming/smartphone-decimeter-2022-1207910d9504/receipt.json",\n        "outputs/e9_mle_bench/modal_streaming/freesound-audio-tagging-2019-c160e87615be/receipt.json"\n      ],\n      "fresh_merged_vllm_arm": {\n        "arm_id": "e9_merged_vllm_seed809_v1",\n        "attempted_or_terminal_union_count": 58,\n        "claim_boundary": "These are fresh one-competition pilots from a separate merged-vLLM arm. Their scores are not unioned with the legacy Tinker-sampled 40/75 coverage and do not constitute an E9 suite score.",\n        "is_full_suite_score": false,\n        "legacy_tinker_coverage_increment": 0,\n        "local_hardening": {\n          "controller_and_arm_tests_passed": 46,\n          "fresh_sol_review_verdict": "ship",\n          "full_v3_success_path_complete": true,\n          "legacy_streaming_tests_passed": 57,\n          "modal_sdk_tests_passed": 12,\n          "paid_launch_enabled": false,\n          "remote_source_gpu_generation_enabled": false,\n          "reviewed_file_hashes": {\n            "e9_merged_vllm_arm.py": "15c1522fbea6227e3dab67d73248fdcb9a02a3bbae127a9f1774962afca18394",\n            "e9_merged_vllm_pilot_control.py": "3af91e5dd449a013b267e0d9ea1e7c32c0e780467606cbefe04b2d48f8b5d3ee",\n            "modal_e9_mle_bench_streaming.py": "088876ba2550c45889689de7fd94a20cad65a58cd5961b400531fd5a2fb462ce",\n            "test_e9_merged_vllm_arm.py": "1beba09e9b9f88c4807e2fb81618e35aeff35e0bde412c5b474a5ded380ac23e",\n            "test_e9_merged_vllm_pilot_control.py": "d8c1313b6b86fd8b1c1ae05ab58a0f8fabe7ba4cdac8be263b4e552f0e66f9e9",\n            "test_modal_e9_mle_bench_streaming.py": "672d8f730b669e20e445439655610eaef31513176d0ce71b1f6457e2cb5d3686"\n          },\n          "status": "REVIEW_PASS_FULL_V3_LOCAL_UNDEPLOYED_FROZEN",\n          "tests_passed": 115\n        },\n        "pilot_count": 7,\n        "remaining_unattempted_union_count": 17,\n        "score": null,\n        "terminal_receipts": [\n          {\n            "competition_id": "hotel-id-2021-fgvc8",\n            "competition_score": null,\n            "receipt": "outputs/e9_mle_bench/merged_vllm/hotel-id-2021-fgvc8-ed92df9f6c44/receipt.json",\n            "status": "NATIVE_SINGLE_COMPETITION_INVALID"\n          },\n          {\n            "competition_id": "imet-2020-fgvc7",\n            "competition_score": null,\n            "receipt": "outputs/e9_mle_bench/merged_vllm/imet-2020-fgvc7-9e3b7fa50417/receipt.json",\n            "status": "NATIVE_SINGLE_COMPETITION_INVALID"\n          },\n          {\n            "competition_id": "predict-volcanic-eruptions-ingv-oe",\n            "competition_score": null,\n            "receipt": "outputs/e9_mle_bench/merged_vllm/predict-volcanic-eruptions-ingv-oe-06379fb32587/receipt.json",\n            "status": "NATIVE_SINGLE_COMPETITION_INVALID"\n          },\n          {\n            "competition_id": "alaska2-image-steganalysis",\n            "competition_score": null,\n            "receipt": "outputs/e9_mle_bench/merged_vllm/alaska2-image-steganalysis-16967d82beeb/receipt.json",\n            "status": "NATIVE_SINGLE_COMPETITION_INVALID"\n          },\n          {\n            "competition_id": "hubmap-kidney-segmentation",\n            "competition_score": null,\n            "receipt": "outputs/e9_mle_bench/merged_vllm/hubmap-kidney-segmentation-6e08e20ea6d4/receipt.json",\n            "status": "NATIVE_SINGLE_COMPETITION_INVALID"\n          },\n          {\n            "above_median": false,\n            "competition_id": "h-and-m-personalized-fashion-recommendations",\n            "competition_score": 0.02132,\n            "receipt": "outputs/e9_mle_bench/merged_vllm/h-and-m-personalized-fashion-recommendations-33d90f35410c/receipt.json",\n            "status": "NATIVE_SINGLE_COMPETITION_GRADED",\n            "valid_submission": true\n          },\n          {\n            "competition_id": "vesuvius-challenge-ink-detection",\n            "competition_score": null,\n            "receipt": "outputs/e9_mle_bench/merged_vllm/vesuvius-challenge-ink-detection-83d8678a457b/receipt.json",\n            "status": "NATIVE_SINGLE_COMPETITION_INVALID"\n          }\n        ]\n      },\n      "lane": "E9",\n      "latest_execution_control_receipt": "outputs/e9_mle_bench/modal_streaming/_pending/plant-pathology-2021-fgvc8-fc-01M16YC7QCNDSS0MPSY0YTYKG2-cancellation-receipt.json",\n      "latest_legacy_competition": {\n        "above_median": false,\n        "any_medal": false,\n        "competition_id": "freesound-audio-tagging-2019",\n        "deterministic_repair": "streamed_unique_freesound_wavs_with_ordered_multilabel_logloss_submission",\n        "is_lower_better": false,\n        "receipt": "outputs/e9_mle_bench/modal_streaming/freesound-audio-tagging-2019-c160e87615be/receipt.json",\n        "receipt_embedded_sha256": "8e07fee28c1e53ef7f62520cb13c6610ff464835a67b7f3fd0759634344fe94f",\n        "receipt_sha256": "844cf17b430d2e6a84d6f2810fb095c6e2a74c6bbff1bf9de81a4c0abf370f19",\n        "score": 0.12497,\n        "valid_submission": true\n      },\n      "name": "MLE-bench",\n      "native_grade_coverage": "40/75 unique competitions",\n      "receipt_inventory": "97 receipts across 50 competition IDs; 41 graded receipts representing 40 unique competitions",\n      "remaining_breakdown": "10 competition IDs have only failed receipts and no saved submission; 25 competition IDs have no run receipt",\n      "remaining_requirement": "35 legacy competitions lack native grades; original sampler unavailable; separate merged arm is frozen.",\n      "remaining_without_native_grade": 35,\n      "result": "40/75 competitions with native grades; suite score unavailable",\n      "score": null,\n      "terms_receipt": "outputs/e9_mle_bench/kaggle_rule_acceptance_receipt_2026-08-22.json",\n      "work_status": "LOCALLY_RECONCILED_FOR_CURRENT_COMPLETION_WINDOW"\n    },\n    {\n      "access_request": "https://huggingface.co/datasets/ai-safety-institute/AgentHarm/discussions/9#6a9251ec206b2a11e4b13108",\n      "benchmark_status": "BLOCKED_EXTERNAL",\n      "blocker": "Private AgentHarm tasks and official native grader are absent.",\n      "lane": "E10",\n      "name": "AgentHarm",\n      "remaining_requirement": "Private held-out task files and authorized native grading route.",\n      "result": "No private-suite result",\n      "score": null,\n      "work_status": "WAITING_PROVIDER"\n    },\n    {\n      "benchmark_status": "SCORED_EXACT_SUITE",\n      "lane": "E11",\n      "name": "VerilogEval",\n      "receipt": "outputs/modal_e1_e14/2026-08-16/e11_full_receipt.json",\n      "remaining_requirement": "None for this recorded single-seed evaluation; 129/311 is noncanonical sensitivity only.",\n      "result": "129/312 = 41.35% pass@1",\n      "scope": "129/312 canonical raw",\n      "score": 0.41346153846153844,\n      "work_status": "LOCALLY_TERMINAL"\n    },\n    {\n      "access_request": "https://huggingface.co/datasets/AfterQuery/App-Bench/discussions/2#6a9251eccd8eaaf580d376b6",\n      "additional_access_request": "https://github.com/AfterQuery/appbench.ai-docs/issues/1",\n      "benchmark_status": "BLOCKED_EXTERNAL",\n      "blocker": "Official deployment, task artifacts, licence, provider trust root, and signed native result remain absent. The local intake now validates the six-task, best-of-three, dual-grader plus adjudication protocol and accepts a finite score only from a fully bound provider-signed result.",\n      "followup_message_id": "1a04b91e262745b6",\n      "lane": "E12",\n      "name": "AppBench",\n      "remaining_requirement": "Official deployment, task artifacts and native grading route.",\n      "result": "No exact-suite result",\n      "score": null,\n      "signed_result_collector": "zvf-program/flagship/pavlov_appbench_openreward_games_adapter.py",\n      "work_status": "WAITING_PROVIDER"\n    },\n    {\n      "additional_access_request": "https://github.com/EnvCommons/wordle/issues/3",\n      "benchmark_status": "BLOCKED_EXTERNAL",\n      "blocker": "The provider-defined immutable held-out OpenReward Games suite remains absent. Account onboarding is complete, but the authenticated 381-environment registry returned zero matches. Canonical score-null request construction and provider-signed result intake are now implemented; no runnable provider suite, trust root, native grading contract, or signed result has been granted.",\n      "followup_message_id": "1a04c1472eafad91",\n      "lane": "E13",\n      "name": "OpenReward Games",\n      "openreward_profile": "https://openreward.ai/arvindcr4",\n      "openreward_state": "PROFILE_ACTIVE",\n      "openreward_username": "arvindcr4",\n      "remaining_requirement": "Provider-defined immutable held-out games suite and grading contract.",\n      "result": "No exact-suite result",\n      "score": null,\n      "signed_result_collector": "zvf-program/flagship/e13_openreward_games_local_runner.py",\n      "work_status": "LOCAL_SETUP_READY_PROVIDER_INPUT_REQUIRED"\n    },\n    {\n      "benchmark_status": "BLOCKED_EXTERNAL",\n      "blocker": "The private hosted Epoch FrontierMath evaluation is unavailable.",\n      "followup_message_id": "1a04b91eb88ae0a6",\n      "lane": "E14",\n      "name": "FrontierMath",\n      "remaining_requirement": "Authorized hosted/private Epoch evaluation.",\n      "result": "No private-suite result",\n      "score": null,\n      "work_status": "WAITING_PROVIDER"\n    }\n  ],\n  "live_checks": {\n    "checked_at_utc": "2026-09-05T02:44:18.662437+00:00",\n    "colab_sessions": {\n      "exit_code": 0,\n      "output": "[colab] No active sessions found on server."\n    },\n    "hf_adapter": {\n      "commit": "64444133c55d88c3f1bf0df8a2f5d7ac646125c8",\n      "files": [\n        {\n          "bytes": 953,\n          "name": "adapter_config.json"\n        },\n        {\n          "bytes": 2245975768,\n          "name": "adapter_model.safetensors"\n        }\n      ],\n      "repo": "arvindcr4/pavlov-portfolio-qwen36-seed809-stepfinal-tinker-cf0ad8c1-1f1b-5ff-9f777c4018b6",\n      "status": "PIN_AND_FILE_METADATA_VERIFIED",\n      "weight_redownload_performed": false\n    },\n    "mail_check": {\n      "after": "2026-08-30",\n      "matching_non_self_messages": 1,\n      "method": "Gmail connector, read-only",\n      "note": "Only an unrelated AI newsletter matched; no email was sent.",\n      "provider_access_grants_found": 0,\n      "query_scope": [\n        "SDAB",\n        "WebBench",\n        "LifeSciBench",\n        "AgentHarm",\n        "AppBench",\n        "OpenReward",\n        "FrontierMath"\n      ]\n    },\n    "modal_apps": [\n      {\n        "app_id": "ap-EMnfdTwXzcPwAwVzP4ONyG",\n        "created_at": "2026-08-16 14:10:42+05:30",\n        "description": "pavlov-e1-swe-bench-pro",\n        "state": "deployed",\n        "stopped_at": null,\n        "tasks": "0"\n      },\n      {\n        "app_id": "ap-Jp9xtm3vsk7nMeNhARfvFI",\n        "created_at": "2026-08-16 23:38:32+05:30",\n        "description": "pavlov-e1-swe-bench-pro-full-native",\n        "state": "deployed",\n        "stopped_at": null,\n        "tasks": "0"\n      },\n      {\n        "app_id": "ap-mZ7F0ZKFUH24EuC3Z0gdOv",\n        "created_at": "2026-08-22 12:58:26+05:30",\n        "description": "__harbor__",\n        "state": "deployed",\n        "stopped_at": null,\n        "tasks": "0"\n      },\n      {\n        "app_id": "ap-VhlFccO5n0Vp1fr5ZpSOlc",\n        "created_at": "2026-08-22 12:59:58+05:30",\n        "description": "swe-bench-pro-eval",\n        "state": "deployed",\n        "stopped_at": null,\n        "tasks": "0"\n      },\n      {\n        "app_id": "ap-9WyfGx9kZCTRPuUD4L8vgA",\n        "created_at": "2026-08-22 16:40:25+05:30",\n        "description": "pavlov-e5-apex-environment",\n        "state": "deployed",\n        "stopped_at": null,\n        "tasks": "0"\n      },\n      {\n        "app_id": "ap-rWDFlUp4ZRyOinWm09dFhR",\n        "created_at": "2026-08-29 17:32:41+05:30",\n        "description": "pavlov-e9-mle-bench-streaming",\n        "state": "deployed",\n        "stopped_at": null,\n        "tasks": "0"\n      }\n    ],\n    "new_experiment_launches": 0,\n    "new_model_calls": 0,\n    "new_paid_compute_allocations": 0,\n    "public_access_requests": [\n      {\n        "comments": [\n          {\n            "created_at": "2026-08-24T06:18:29Z",\n            "user": "arvindcr4"\n          },\n          {\n            "created_at": "2026-08-29T03:28:43Z",\n            "user": "arvindcr4"\n          }\n        ],\n        "non_owner_comments": 0,\n        "query_succeeded": true,\n        "url": "https://github.com/Halluminate/WebBench/issues/2"\n      },\n      {\n        "comments": [],\n        "non_owner_comments": 0,\n        "query_succeeded": true,\n        "url": "https://github.com/AfterQuery/appbench.ai-docs/issues/1"\n      },\n      {\n        "comments": [],\n        "non_owner_comments": 0,\n        "query_succeeded": true,\n        "url": "https://github.com/EnvCommons/wordle/issues/3"\n      }\n    ],\n    "tinker_checkpoint": {\n      "exit_code": 1,\n      "output": "Error: Checkpoint not found: tinker://cf0ad8c1-1f1b-5ff3-8bd7-2a0bf232657b:train:0/sampler_weights/seed809_final"\n    },\n    "tinker_checkpoint_list": {\n      "exit_code": 0,\n      "output": "{\\n  \\"run_id\\": \\"cf0ad8c1-1f1b-5ff3-8bd7-2a0bf232657b:train:0\\",\\n  \\"checkpoints\\": []\\n}"\n    }\n  },\n  "overall_status": "INCOMPLETE_BLOCKED",\n  "partial_lanes": 5,\n  "results_origin": "Historical native execution receipts rechecked locally on 2026-09-05; no new benchmark execution.",\n  "schema_version": "e1-e14-results-reconciliation-v1",\n  "source_status_recorded_at": "2026-08-30T20:54:54Z",\n  "validation": {\n    "checks_passed": 394,\n    "completion_gate_unit_tests_passed": 15,\n    "failed_checks": 0,\n    "recovered_files": 4\n  }\n}\n'
EXPECTED_SHA256 = '8e81424ebe4ed7893cca67a92f6edb2e7611ff47c496a71920e5c543936b1090'
assert hashlib.sha256(SNAPSHOT_JSON.encode()).hexdigest() == EXPECTED_SHA256
audit = json.loads(SNAPSHOT_JSON)
print("Snapshot:", audit["as_of_utc"])
print("Source result status:", audit["source_status_recorded_at"])
print("Local evidence checks passed:", audit["validation"]["checks_passed"])

Snapshot: 2026-09-05T02:44:27.910654+00:00
Source result status: 2026-08-30T20:54:54Z
Local evidence checks passed: 394


## Results

Only rows marked **Full-suite result** contain a suite score. All other numbers describe partial tasks or recovery attempts.

In [2]:
def table(headers, rows):
    head = "".join("<th>" + escape(str(x)) + "</th>" for x in headers)
    body = "".join("<tr>" + "".join("<td>" + escape(str(x)) + "</td>" for x in row) + "</tr>" for row in rows)
    display(HTML("<style>table.evidence{border-collapse:collapse;width:100%;font:14px system-ui} .evidence td,.evidence th{padding:10px;text-align:left;border-bottom:1px solid #cbd5e1;vertical-align:top}.evidence th{background:#e2e8f0;color:#0f172a}.evidence tr:nth-child(even){background:#f8fafc;color:#0f172a}</style><table class=evidence><thead><tr>"+head+"</tr></thead><tbody>"+body+"</tbody></table>"))

rows = []
for lane in audit["lanes"]:
    state = "Full-suite result" if lane["score"] is not None else ("Partial" if lane["benchmark_status"].startswith("PARTIAL") else "Blocked")
    rows.append([lane["lane"], lane["name"], lane["result"], state])
table(["Experiment", "Benchmark", "Observed result", "Suite status"], rows)

Experiment,Benchmark,Observed result,Suite status
E1,SWE-bench Pro,2/731 = 0.274% pass@1,Full-suite result
E2,FrontierSWE,1/17 tasks; replay normalized score 0.8628,Partial
E3,SDAB,No exact-suite result,Blocked
E4,BankerToolBench,1/100 tasks; recovery metric 0.3115,Partial
E5,APEX-Agents,11/480 attempted; 7 native-scored; prefix mean 0.050505,Partial
E6,WebBench,No exact-suite result,Blocked
E7,BinaryAudit,1/46 tasks; verifier reward 0.0 after agent error,Partial
E8,LifeSciBench,0/750 tasks,Blocked
E9,MLE-bench,40/75 competitions with native grades; suite score unavailable,Partial
E10,AgentHarm,No private-suite result,Blocked


### Recompute the two complete outcomes

The embedded pass/fail vectors were read directly from the saved E1 native aggregate and E11 verifier receipts. These are historical measurements.

In [3]:
e1_passes = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
e11_verdicts = {'code-complete-iccad2023': ['PASS', 'PASS', 'PASS', 'FAIL', 'PASS', 'PASS', 'PASS', 'PASS', 'FAIL', 'FAIL', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'FAIL', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'FAIL', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'PASS', 'PASS', 'PASS', 'PASS', 'FAIL', 'PASS', 'PASS', 'FAIL', 'FAIL', 'PASS', 'PASS', 'FAIL', 'PASS', 'PASS', 'PASS', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'PASS', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'PASS', 'PASS', 'FAIL', 'PASS', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'PASS', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL'], 'spec-to-rtl': ['PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'PASS', 'FAIL', 'PASS', 'PASS', 'PASS', 'PASS', 'FAIL', 'PASS', 'FAIL', 'PASS', 'PASS', 'FAIL', 'PASS', 'PASS', 'PASS', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'PASS', 'PASS', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'PASS', 'PASS', 'PASS', 'FAIL', 'FAIL', 'PASS', 'PASS', 'FAIL', 'FAIL', 'PASS', 'PASS', 'FAIL', 'FAIL', 'PASS', 'PASS', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'PASS', 'FAIL', 'PASS', 'PASS', 'PASS', 'PASS', 'FAIL', 'PASS', 'PASS', 'FAIL', 'PASS', 'FAIL', 'PASS', 'FAIL', 'PASS', 'PASS', 'FAIL', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'PASS', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL', 'FAIL']}
lanes = {r["lane"]: r for r in audit["lanes"]}
assert len(e1_passes) == 731
assert all(isinstance(x, bool) for x in e1_passes)
e1_score = sum(e1_passes) / len(e1_passes)
all_verdicts = [v for values in e11_verdicts.values() for v in values]
assert len(all_verdicts) == 312 and set(all_verdicts) <= {"PASS", "FAIL"}
e11_score = all_verdicts.count("PASS") / len(all_verdicts)
assert math.isclose(e1_score, lanes["E1"]["score"])
assert math.isclose(e11_score, lanes["E11"]["score"])
assert len(lanes) == 14 and sum(r["score"] is not None for r in lanes.values()) == 2
print(f"E1: {sum(e1_passes)}/{len(e1_passes)} = {100*e1_score:.6f}%")
print(f"E11: {all_verdicts.count("PASS")}/{len(all_verdicts)} = {100*e11_score:.6f}%")
print("Twelve suite scores remain null.")

E1: 2/731 = 0.273598%
E11: 129/312 = 41.346154%
Twelve suite scores remain null.


### E9 coverage by inference arm

Competition metrics use different scales, so averaging their raw scores is not a benchmark aggregate. The merged-vLLM pilot contributes zero to the legacy Tinker arm’s coverage.

In [4]:
arm_rows = []
for name, arm in audit["e9_arms"].items():
    assert arm["native_graded_competitions"] == len(set(arm["graded_competition_ids"]))
    assert arm["score"] is None
    arm_rows.append([name, arm["receipt_count"], arm["unique_competitions"], arm["native_graded_competitions"], "Unavailable"])
table(["Arm", "Receipts", "Competition IDs", "IDs with native grade", "Full-suite score"], arm_rows)
print("Legacy competitions still without native grade:", 75-audit["e9_arms"]["modal_streaming"]["native_graded_competitions"])

Arm,Receipts,Competition IDs,IDs with native grade,Full-suite score
merged_vllm,7,7,1,Unavailable
modal_streaming,97,50,40,Unavailable


Legacy competitions still without native grade: 35


## Colab, Tinker and remaining work

The live Tinker checkpoint lookup returned not found, and its checkpoint list was empty. Hub metadata for the pinned adapter remains accessible. Colab had no active session. Earlier Colab canaries failed before producing benchmark results. No new experiment was launched by this audit.

In [5]:
table(["Experiment", "Requirement to continue"], [[r["lane"]+" — "+r["name"], r["remaining_requirement"]] for r in audit["lanes"] if r["score"] is None])
budget=audit["budget"]
print(f"Saved budget ledger: ${budget["recorded_remaining_usd"]:.4f} remaining of ${budget["authorized_incremental_usd"]:.2f} additional allowance.")
print("Ledger timestamp:", budget["ledger_recorded_at"])
print(budget["boundary"])

Experiment,Requirement to continue
E2 — FrontierSWE,Revision-bound benchmark authorization and 16 remaining tasks; original Tinker checkpoint unavailable.
E3 — SDAB,"Private 80-task bundle, runtime/reset contract and native grader."
E4 — BankerToolBench,Working model/verifier endpoint and budget: the prior native-grader-only estimate exceeds the recorded remaining cap.
E5 — APEX-Agents,"Working inference runtime, full auxiliary assets, sufficient budget and a declared execution protocol."
E6 — WebBench,"Official live environment, reset procedure, ground truth and native scorer."
E7 — BinaryAudit,"Revision-bound benchmark authorization, working model runtime and the remaining 45 tasks."
E8 — LifeSciBench,Official task package and native grader.
E9 — MLE-bench,35 legacy competitions lack native grades; original sampler unavailable; separate merged arm is frozen.
E10 — AgentHarm,Private held-out task files and authorized native grading route.
E12 — AppBench,"Official deployment, task artifacts and native grading route."


Saved budget ledger: $44.3699 remaining of $50.00 additional allowance.
Ledger timestamp: 2026-08-30T02:14:48Z
Historical conservative accounting, not a refreshed invoice or Colab balance. No new paid allocation in this task.


## Takeaways

E1 has a 0.274% full-suite result and E11 has a 41.35% canonical result. The other twelve lanes remain unfinished. Completing them requires the missing provider assets or evaluation access, a working inference runtime with the checkpoint provenance preserved, and sufficient authorized budget.

Four E9 files were restored only when their bytes matched existing SHA-256 hashes. The first Spooky Author run still lacks its complete local submission; a later run retains a full submission. These repairs do not create new grades.

Read `E1_E14_Results.md`, `results.json`, `live_execution_check.json`, `validation.json`, `evidence_recovery.json`, and `source_manifest.json` alongside this notebook for the detailed evidence boundary.